[workspace]
members = [
    "runtime",
    "runtime-loader",
    "client",
    "keymanager-client",
    "keymanager-api-common",
    "keymanager-lib",
    "tools",

    # Test runtimes.
    "tests/runtimes/simple-keyvalue",
    "tests/runtimes/simple-keymanager",

    # Test clients.
    "tests/clients/simple-keyvalue",
    "tests/clients/simple-keyvalue-enc",
    "tests/clients/test-long-term",
]

[profile.release]
panic = "abort"
